[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tlaloc_cdn_builder"]

[tool.setuptools.package-data]
tlaloc_cdn_builder = ["functions/*"]